### ISSUE TITLE
No help documentation for config page

### ISSUE THREAD

**Issue by mabahj** [biouno/pbs-plugin#6]
There is no documentation for the PBS settings on the configuration page. This is not very important, but it would be nice with some text. Also, when I click the question mark, another jenkins page is loaded on top of the existing page. See attached image.

![capture](https://cloud.githubusercontent.com/assets/11989549/7197115/3c62f23e-e4dd-11e4-8a39-337201342a56.PNG)

**Comment by kinow** [comment]
Related to #9

**Comment by kinow** [comment]
Being worked as part of #9
